#! /usr/bin/env bash

echo "Running: fetch --all --prune"
git fetch --all --prune || { >&2 echo "Failed to fetch!"; exit 1; }

echo "Running: git pull"
git pull || { >&2 echo "Failed to pull!"; exit 1; }
